// FreefallGame on Base mainnet. ABI derived from contracts/FreefallGame.sol
// (verified source at this address on Blockscout/Basescan).

import { Attribution } from "ox/erc8021";

export const FREEFALL_ADDRESS =
  "0x0ab513621ecedb464d6620bdb77a88e393a141ae" as const;

// ERC-8021 builder-code attribution. This is our builder code from base.dev
// (Settings → Builder Code), appended via dataSuffix to the calldata of every
// transaction this app sends so the txs are attributed to us onchain. The
// suffix is generated by ox's canonical-registry encoder (schema 0) per the
// base.dev integration guide — do not hand-encode it.
// https://docs.base.org/apps/builder-codes/app-developers
export const BUILDER_CODE = "bc_7a5r3efc";
export const BUILDER_SUFFIX = Attribution.toDataSuffix({ codes: [BUILDER_CODE] });

export const freefallAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "GameStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "uint96", name: "score", type: "uint96" },
      { indexed: false, internalType: "bool", name: "newBest", type: "bool" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "ScoreAttested",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint96", name: "score", type: "uint96" }],
    name: "attestScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "bestScore",
    outputs: [{ internalType: "uint96", name: "", type: "uint96" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "gamesStarted",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTop10",
    outputs: [
      {
        components: [
          { internalType: "address", name: "player", type: "address" },
          { internalType: "uint96", name: "score", type: "uint96" },
        ],
        internalType: "struct FreefallGame.Entry[10]",
        name: "",
        type: "tuple[10]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "sessionOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "startGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSessions",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const FREEFALL = {
  address: FREEFALL_ADDRESS,
  abi: freefallAbi,
} as const;

export function truncAddr(addr: string): string {
  return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
}

export function basescanTxUrl(hash: string): string {
  return `https://basescan.org/tx/${hash}`;
}
